### ISSUE TITLE
Provided source code does not work properly in the debug mode (Microsoft Visual Studio)

### ISSUE THREAD

**Issue by Yanjun7J** [alecjacobson/geometry-processing-introduction#39]
After I clone and run the original code in the debug mode. It shows the following debug error:
![image](https://user-images.githubusercontent.com/33232325/35952353-a5f8bb8a-0c4d-11e8-82f8-17f49970f5de.png)

And then I tried to initialize the chi with 0, the program works fine but the bunny is not showing:
![image](https://user-images.githubusercontent.com/33232325/35952460-1c57951c-0c4e-11e8-8371-8f19d81a2483.png)

**Comment by alecjacobson** [comment]
Ah, that's something that's usually just a warning... I'll fixe the code
for next year.
-A

**Comment by Yanjun7J** [comment]
Sorry, I am not sure whether you see the second part or not. I tried to initialize the Chi variable with 0 - it does not complain anymore but it still doesn't show the bunny image in debug mode.... I think that's something more than just a warning?

**Comment by alecjacobson** [comment]
Ah. I did miss that. That’s strange. Did you see if any other windows users
have this problem? Can you check that the bunny file is being read in
correctly?

**Comment by Yanjun7J** [comment]
Sorry for the late response but I have just got the chance to check it on someone else's Windows running with VS2015 (mine is in VS2017). It still doesn't work properly in the debug mode (the release mode works properly) - the bunny doesn't show. And I recheck the requirement you specify in the introduction section:
![image](https://user-images.githubusercontent.com/33232325/36356090-c84691e2-14ba-11e8-9697-c3e144970923.png)
I suspect if it is something related to the mode thing - 64bit vs 32bit? Both of me and my friend we build it in 32bit mode. So we tried to build it in 64bit mode but it failed with the following error message:
 module machine type 'x64' conflicts with target machine type 'X86'
which I don't know how to solve properly...
And I also don't know whether the mode thing actually matters (the 32bit mode vs. the 64bit mode) because all other assignments so far works properly by being built in 32bit mode for me (only except this one and only for debug mode)...

**Comment by alecjacobson** [comment]
I don't use windows, but I believe libigl expects 64bit if that helps.

**Comment by Yanjun7J** [comment]
Okay... Then what platform (e.g. the version of cmake and operating system) are the assignments going to be tested on? Do I need to switch my development environment to it?

**Comment by Yanjun7J** [comment]
Okay! Thank you.
