### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by masyrezaei** [alecjacobson/geometry-processing-introduction#40]
Hi
I only want to calculate E F G e f g for a mesh. I did it with thousands methods (discrete or using surface fitting) but the results aren't good. 
I am using Windows. could you please help me how I can use your code?
Thanks

**Comment by alecjacobson** [comment]
This repository is for an course _assignment_. None of the functions are implemented. If you'd like, you could read the README.md and try implementing them yourself.
