### ISSUE TITLE
Testing the Code

### ISSUE THREAD

**Issue by AdrianShe** [alecjacobson/geometry-processing-introduction#44]
Hello, just thinking about testing the code, it should be possible to test the code with the other meshes given in the shared/data directory but I was wondering if there a way to create your own triangle mesh files as well? Thanks.

**Comment by alecjacobson** [comment]
Hi Adrian,
There are lots of mesh editing tools online: Autodesk Maya (free for students), tinkerCad (free online), Blender.

You can also grab models from online repositories for example https://www.thingiverse.com

Do beware that .stl files are raw "triangle soups", so vertices at the same position are not connected.

You could use MeshLab (free) to merge them, or just stick to .obj files.

**Comment by juliagilenko** [comment]
I stumbled on a cube in case you'd like some really simple ready-made input to test with:
https://en.wikipedia.org/wiki/OFF_(file_format)

**Comment by AdrianShe** [comment]
Thanks for the suggestions!
