### ISSUE TITLE
make error after running cmake

### ISSUE THREAD

**Issue by AdamSturge** [alecjacobson/geometry-processing-introduction#6]
The steps for setting up assignment 0 state to run cmake .. then make. I've managed to get cmake to run but make gives me an error. Having never used these tools before I assume there's something simple I'm missing.
![capture](https://cloud.githubusercontent.com/assets/3497703/21940191/2f15c174-d991-11e6-8082-1f3deb32f1b1.PNG)

**Comment by mtao** [comment]
CMake has made a visual studio project so you can load a visual studio project in that directory.
If you really want to use `make` on windows you have to set the generator to "Unix Makefiles":

`cmake .. -G"Unix Makefiles"`
