### ISSUE TITLE
Build issue for "introduction" project

### ISSUE THREAD

**Issue by AdamSturge** [alecjacobson/geometry-processing-introduction#7]
After I ran  CMake I can open introduction.sln in visual studio 2015. However not all the projects build correctly. Has anyone else run into this?

------ Rebuild All started: Project: introduction, Configuration: Debug Win32 ------
6>  Building Custom Rule C:/UoT-Masters/Geometry-Processing/geometry-processing-introduction/CMakeLists.txt
6>  CMake does not need to re-run because C:\UoT-Masters\Geometry-Processing\geometry-processing-introduction\build\CMakeFiles\generate.stamp is up-to-date.
6>cl : Command line error D8021: invalid numeric argument '/Wno-deprecated-declarations'

**Comment by alecjacobson** [comment]
Could you try building the libigl tutorial from scratch ?

I'd like to find out if this is a problem with my cmake or libigl's (I can
help fix it in either case).

**Comment by mtao** [comment]
Isn't this an issue with MSVC not supporting theno-deprecated-declarations argument? I suspect this patch to shared would work?


[msvc_no-dep-decs.txt](https://github.com/alecjacobson/geometry-processing-introduction/files/705718/msvc_no-dep-decs.txt)

**Comment by AdamSturge** [comment]
@mtao I'm sorry but sure what to do with that text file. Could you elaborate?

**Comment by AdamSturge** [comment]
So I think I have it working by following this instruction through visual studio project properties. http://stackoverflow.com/questions/13717551/1cl-command-line-error-d8021-invalid-numeric-argument-wno-deprecated-er

I'm not sure if removing that flag will cause things to break down the line at runtime

**Comment by mtao** [comment]
the file was a patch on how to change the CMakeLists.txt to not use -Wno-deprecated-declarations when using MVSC.

It won't cause any issues, it's just a deprecation warning.
