### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by AdamSturge** [alecjacobson/geometry-processing-introduction#8]
My code for assignment 0 compiles and runs, but I don't see the rabbit.
![capture](https://cloud.githubusercontent.com/assets/3497703/21956897/8cdd7bea-da58-11e6-8f30-cbabf12e1370.PNG)

**Comment by manderelee** [comment]
Hm, I'm not sure if this would necessarily help, but have you tried dragging around the image? My bunny is not centered on my screen either, it's sort of floating up top, with cut-off ears. Wondering if yours might be totally off-screen.

**Comment by AdamSturge** [comment]
Just tried spamming drags North,South,East, and West but no bunny.

**Comment by manderelee** [comment]
Are there any error messages on the console?

**Comment by AdamSturge** [comment]
Red pen is my addition (not want to be accused of sharing my answer)

![capture](https://cloud.githubusercontent.com/assets/3497703/21957066/cfe7faa6-da5c-11e6-88ca-41d87409106d.PNG)

**Comment by alecjacobson** [comment]
I assume that the file is loading correctly if you can compute
edges/euler_characteristic.

Could you try compiling and running the libigl tutorial (independently)?
Let's first see if this is a libigl issue or an issue with this assignment.
-A

**Comment by mtao** [comment]
I believe this might be the issue kevin submitted a pull request for:
https://github.com/libigl/libigl/pull/443

**Comment by AdamSturge** [comment]
Confirmed that the bug does not happen when I compile for Release instead of Debug
