### ISSUE TITLE
Could not run introduction.exe

### ISSUE THREAD

**Issue by Ming-Yeung-Alfred-Meng** [alecjacobson/geometry-processing-introduction#84]
![image](https://user-images.githubusercontent.com/81248498/190444535-09fe4475-0a10-48bf-a71f-121d94e6fdce.png)
![image](https://user-images.githubusercontent.com/81248498/190448122-73b320d6-c936-4bcd-a3be-3979a1fa54cf.png)

I am on Windows 11 and VS 2022. I have not made any implementations and I got this error when running introduction.exe. What should I do?

![image](https://user-images.githubusercontent.com/81248498/190447508-0d28f4c3-4899-47cb-b66b-be6409e438c2.png)
 These are the messages I got when running cmake. My machine failed the test for CMAKE_HAVE_LIBC_PTHREAD.

**Comment by Ming-Yeung-Alfred-Meng** [comment]
![image](https://user-images.githubusercontent.com/81248498/190447508-0d28f4c3-4899-47cb-b66b-be6409e438c2.png)
 These are the messages I got when running cmake. My machine failed the test for CMAKE_HAVE_LIBC_PTHREAD.

**Comment by Ming-Yeung-Alfred-Meng** [comment]
![image](https://user-images.githubusercontent.com/81248498/190448122-73b320d6-c936-4bcd-a3be-3979a1fa54cf.png)

**Comment by ethanmoran** [comment]
You need to move introduction.exe into the /build directory rather than /build/Debug as it reads the bunny.off file from ../data/bunny.off. You can set the output directory in visual studio as well so you don't have to move it every time

**Comment by Ming-Yeung-Alfred-Meng** [comment]
Thank you!!!
