### ISSUE TITLE
Example showing curves doesn't work

### ISSUE THREAD

**Issue by Tyndall-log** [alecjacobson/geometry-processing-introduction#92]
![image](https://user-images.githubusercontent.com/66102031/215782595-c0e12b9f-305e-4b8b-b0ef-73ec102030fb.png)
Pressing all the shortcuts g, m, and k does not show the results.
Did I set something up wrong?

**Comment by alecjacobson** [comment]
did you implement the solution?

**Comment by Tyndall-log** [comment]
Oh, I'm sorry.
I was mistaken for the "geometry-processing-curvature" repository.
This is a question about the repository.
Does it mean that I have to implement something in the main.cpp of the provided culture solution?
Can't I test the function provided without implementation?
+) What I noticed while looking at the repository is that it is not implemented because it is for students' homework.
Is it right?

**Comment by alecjacobson** [comment]
Yes, that's right. This is a homework assignment for a course.

**Comment by Tyndall-log** [comment]
thank you for the reply.
